import { DB } from "./types";

let uid = 0;
const id = () => `seed-${uid++}`;

export const seedDB: DB = {
  proyectos: [
    {
      id: id(),
      numero: 1,
      nombre: "Trofeos Nankang",
      cliente: "Representante Nankang",
      entregado: true,
      fechaEntrega: "2026-06-27",
      pagado: true,
      fechaPago: "2026-06-27",
      gastos: [
        { id: id(), producto: "Flmnt plateado", precio: 24605, cantidad: 1, pagadoPor: "Juan" },
        { id: id(), producto: "Flmnts negro mate", precio: 21900, cantidad: 2, pagadoPor: "Nico" },
        { id: id(), producto: "La gotita", precio: 3500, cantidad: 1, pagadoPor: "Titi" },
        { id: id(), producto: "Dominio", precio: 8500, cantidad: 1, pagadoPor: "Titi" },
        { id: id(), producto: "Flmnt negro", precio: 19000, cantidad: 1, pagadoPor: "Titi" },
        { id: id(), producto: "Flmnt gris", precio: 22000, cantidad: 0.5, pagadoPor: "Juan" },
        { id: id(), producto: "Flmnt blanco", precio: 22000, cantidad: 0.5, pagadoPor: "Juan" },
        { id: id(), producto: "Flmnt plateado", precio: 22000, cantidad: 0.1, pagadoPor: "Nico" },
      ],
      ingresos: [{ id: id(), producto: "Trofeo", precio: 50000, cantidad: 6 }],
      filamentos: [],
      tareas: [],
    },
    {
      id: id(),
      numero: 2,
      nombre: "Trofeos Nankang 2",
      cliente: "Representante Nankang",
      entregado: false,
      fechaEntrega: "",
      pagado: false,
      fechaPago: "",
      gastos: [],
      ingresos: [{ id: id(), producto: "Trofeo", precio: 50000, cantidad: 18 }],
      filamentos: [],
      tareas: [],
    },
    {
      id: id(),
      numero: 3,
      nombre: "Trofeos Pole",
      cliente: "Juan",
      entregado: false,
      fechaEntrega: "",
      pagado: false,
      fechaPago: "",
      gastos: [{ id: id(), producto: "Flmnt", precio: 24605, cantidad: 1, pagadoPor: "Juan" }],
      ingresos: [{ id: id(), producto: "Trofeo Winston", precio: 50000, cantidad: 2 }],
      filamentos: [],
      tareas: [],
    },
    {
      id: id(),
      numero: 4,
      nombre: "Soportes",
      cliente: "Joaquín Bua",
      entregado: false,
      fechaEntrega: "",
      pagado: false,
      fechaPago: "",
      gastos: [
        { id: id(), producto: "Flmnt", precio: 23700, cantidad: 1.78, pagadoPor: "Juan" },
        { id: id(), producto: "Iman Ceramico", precio: 15300, cantidad: 1, pagadoPor: "Juan" },
      ],
      ingresos: [
        { id: id(), producto: "Soporte Solo", precio: 52850, cantidad: 6 },
        { id: id(), producto: "Soporte Lisso", precio: 68000, cantidad: 4 },
        { id: id(), producto: "Soporte Volante", precio: 30200, cantidad: 2 },
      ],
      filamentos: [],
      tareas: [],
    },
    {
      id: id(),
      numero: 5,
      nombre: "Trofeos Pistón",
      cliente: "",
      entregado: false,
      fechaEntrega: "2026-12-01",
      pagado: false,
      fechaPago: "",
      gastos: [],
      ingresos: [{ id: id(), producto: "Trofeo P. 1/2/3", precio: 60000, cantidad: 3 }],
      filamentos: [],
      tareas: [],
    },
    {
      id: id(),
      numero: 6,
      nombre: "Soporte Starlink Amarok",
      cliente: "",
      entregado: false,
      fechaEntrega: "",
      pagado: false,
      fechaPago: "",
      gastos: [{ id: id(), producto: "Flmt", precio: 23700, cantidad: 0.22, pagadoPor: "Juan" }],
      ingresos: [{ id: id(), producto: "Soporte Starlink", precio: 50000, cantidad: 1 }],
      filamentos: [],
      tareas: [],
    },
  ],
  presupuestos: [
    {
      id: id(),
      cliente: "Elio",
      fecha: "2026-07-14",
      items: [{ id: id(), pieza: "Engranaje", cantidad: 10, precio: 47000 }],
    },
  ],
};
